In [1]:
from google.colab import files
uploaded = files.upload()

Saving covid_toy.csv to covid_toy.csv

In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df = pd.read_csv("covid_toy.csv")

In [5]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)
#

AAm Zindgi

In [10]:
#adding simple imputer to fever col
si= SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

#also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [11]:
#ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

#also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

In [18]:
#onehotencoding -> gender city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

#also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])
X_train_gender_city.shape

(80, 4)

In [19]:
#Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

#also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values
X_train_age.shape

(80, 1)

In [21]:
x_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
#also the test data
x_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)
x_train_transformed
#

array([[ 72.       ,  99.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 70.       , 103.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   1.       ],
       [  5.       , 100.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 60.       ,  99.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 20.       , 102.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   1.       ],
       [ 49.       , 102.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 79.       , 100.7260274,   1.       ,   0.       ,   1.       ,
          0.       ,   1.       ],
       [ 47.       , 100.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 34.       , 100.7260274,   0.       ,   0.       ,   0.       ,
          1.       ,   1.       ],
       [ 10.       ,  98.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   1.       ],
       [ 65.       , 101.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 10.       , 100.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 38.       , 100.7260274,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 64.       , 102.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 11.       , 100.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 27.       , 100.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 69.       ,  98.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   1.       ],
       [ 49.       , 101.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 27.       , 100.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 19.       , 101.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [  6.       , 104.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 19.       , 100.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 56.       , 104.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 44.       , 104.       ,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 24.       , 102.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 46.       , 103.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 75.       , 100.7260274,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 66.       ,  99.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 51.       , 101.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   1.       ],
       [ 26.       ,  98.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 48.       , 103.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 19.       , 101.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 47.       , 101.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 81.       ,  98.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   1.       ],
       [ 83.       ,  98.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 83.       , 101.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 82.       , 102.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   1.       ],
       [ 64.       , 101.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 82.       , 100.7260274,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 54.       , 104.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   1.       ],
       [ 25.       , 104.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 40.       ,  98.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   1.       ],
       [ 20.       , 101.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 49.       ,  99.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 55.       , 100.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 25.       ,  99.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   1.       ],
       [ 74.       , 102.       ,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 19.       , 100.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 18.       , 104.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 50.       , 103.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 27.       , 100.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 73.       ,  98.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 80.       , 100.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 51.       , 104.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 83.       , 103.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 80.       ,  98.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 15.       , 101.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 65.       ,  98.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 65.       ,  99.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 11.       , 100.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   1.       ],
       [ 14.       ,  99.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 69.       , 103.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 34.       , 101.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   1.       ],
       [ 75.       , 104.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   1.       ],
       [ 69.       , 102.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 13.       , 100.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   1.       ],
       [ 51.       , 104.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 71.       , 100.7260274,   1.       ,   0.       ,   1.       ,
          0.       ,   1.       ],
       [ 22.       ,  99.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 16.       , 104.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [  5.       ,  98.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   1.       ],
       [ 81.       , 101.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 38.       , 101.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 42.       , 101.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [  8.       , 101.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 23.       ,  98.       ,   1.       ,   0.       ,   0.       ,
          1.       ,   1.       ],
       [ 65.       ,  99.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 23.       , 100.7260274,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 59.       ,  99.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   1.       ],
       [ 71.       ,  98.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   1.       ]])

Mentos Zindagi(using columntransformer)

In [23]:
from sklearn.compose import ColumnTransformer

In [27]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder= 'passthrough')
transformer.fit_transform(X_train).shape

(80, 7)

In [28]:
transformer.fit_transform(X_test).shape

(20, 7)